#************************** makefile for cmd\... ***************************

msg	=..\..\messages
dos	=..\..\dos
inc	=..\..\inc
hinc	=..\..\h

#
#######################	dependencies begin here. #########################
#

all: label.com

label.obj: label.asm    \
  makefile

labelm.obj: labelm.asm  \
  labl.ctl 		\
  makefile             \
  $(inc)\copyrigh.inc   \
  $(inc)\sysmsg.inc     \
  $(inc)\msgserv.asm

label.com: label.obj    \
  labelm.obj            \
  makefile             \
  label.lnk
       link @label.lnk
       exe2bin label.exe LABEL.COM
       del label.exe
       upx --8086 LABEL.COM
       del *.obj
