#************************** makefile for cmd\... ***************************

msg	=..\..\messages
dos	=..\..\dos
inc	=..\..\inc
hinc	=..\..\h

#
#######################	dependencies begin here. #########################
#

all: fdisk.com


fdisk.obj: fdisk.asm
          masm fdisk;

fdisk.com: fdisk.obj
	link fdisk;
	del *.obj
