#************************** makefile for cmd\... ***************************

dos	=..\..\dos
inc	=..\..\inc
hinc	=..\..\h

#
#######################	dependencies begin here. #########################
#

all: bat2exec.com


bat2exec.obj: bat2exec.asm
          tasm bat2exec;

bat2exec.com: bat2exec.obj
	tlink /t bat2exec;
	upx --8086 BAT2EXEC.COM
	del *.obj
	del *.map
