
.SUFFIXES:
.SUFFIXES:	.c .asm .obj .lst .def .lnk .lrf .exe .com

#	Definition for turning OFF high memory allocation
#		HIFLAG = -DNOHIMEM => turns it off
#		HIFLAG =	   => turns on high memory allocation
HIFLAG	      = /DNOHIMEM
#HIFLAG	=

#	Definitions for assembler
#	(using masm 4.00)
MASM	= masm
AFLAGS	= /Mx /t /DI386  /i..\memm $(HIFLAG)
AINC	= ..\memm\vdmseg.inc ..\memm\vdmsel.inc emmdef.inc

#	Definitions for linker for old style .exe files
LINK	 = link
LFLAGS	= /NOI /M
LIBS	=

#	Definitions for librarian
LIB	 = lib

#	Defines for C Compiler
C	= cl
CFLAGS	=/ASw /G2 /Oat /Gs /Ze /Zl /Fc /c

#
# definition of objects
#
OBJS=emmfunct.obj emm40.obj emmp.obj emmsup.obj emmdisp.obj emmdata.obj emminc.obj
LOBJS=emmfunct.obj+emm40.obj+emmp.obj+emmsup.obj+emmdisp.obj+emmdata.obj

emmlib.lib:	$(OBJS)
		del emmlib.lib
		$(LIB) emmlib+$(LOBJS),;
		del *.obj
		del *.lst

emmfunct.obj:	emmfunct.c emm.h
		$(C) $(CFLAGS) emmfunct.c

emm40.obj:	emm40.c emm.h
		$(C) $(CFLAGS) emm40.c

emmp.obj:	emmp.asm $(AINC)
		$(MASM) $(AFLAGS) emmp.asm,emmp.obj,emmp.lst;

emmsup.obj:	emmsup.asm $(AINC)
		$(MASM) $(AFLAGS) emmsup.asm,emmsup.obj,emmsup.lst;

emmdisp.obj:	emmdisp.asm $(AINC)
		$(MASM) $(AFLAGS) emmdisp.asm,emmdisp.obj,emmdisp.lst;

emmdata.obj:	emmdata.asm $(AINC)
		$(MASM) $(AFLAGS) emmdata.asm,emmdata.obj,emmdata.lst;

emminc.obj:	emminc.asm $(AINC)
		$(MASM) $(AFLAGS) emminc.asm,emminc.obj,emminc.lst;

