#************************* makefile for messages **************************

country    =usa-ms

#
#######################	dependencies begin here. #########################
#

all: $(country).idx

$(country).msg: $(country).pre
	copy /b $(country).pre $(country).msg

$(country).idx: $(country).msg
