#************************** makefile for cmd\... ***************************

msg	=..\..\messages
dos	=..\..\dos
inc	=..\..\inc
hinc	=..\..\h

#
#######################	dependencies begin here. #########################
#

all: ansi.com


ansi.obj: ansi.asm
          masm ansi;

ansi.com: ansi.obj
	link ansi;
	exe2bin ansi.exe ANSI.COM
	del ansi.exe
	del *.obj
