#************************** makefile for cmd\... ***************************

msg	=..\..\messages
dos	=..\..\dos
inc	=..\..\inc
hinc	=..\..\h

#
#######################	dependencies begin here. #########################
#

all: reboot.com


reboot.obj: reboot.asm
          masm reboot;

reboot.com: reboot.obj
	link reboot;
	exe2bin reboot.exe REBOOT.COM
	del reboot.exe
	del *.obj
