#************************** makefile for cmd\... ***************************

msg	=..\..\messages
dos	=..\..\dos
inc	=..\..\inc
hinc	=..\..\h

#
#######################	dependencies begin here. #########################
#

all: mem.com


mem.obj: mem.asm
          masm mem;

mem.com: mem.obj
	link mem;
	exe2bin mem.exe MEM.COM
	del mem.exe
	del *.obj
